services:
  hello-world-job:
    build:
      context: ../../..
      dockerfile: src/main/resources/Dockerfile
    depends_on:
      - etcd
    networks:
      - leader-election-network
    environment:
      - ETCD_URL=http://etcd:2379
      - LEADER_ELECTION_KEY=/hello_world_job/leadership
    restart: always

  etcd:
    image: quay.io/coreos/etcd:v3.5.0
    ports:
      - "2379:2379"
      - "2380:2380"
    command:
      - etcd
      - --name
      - s1
      - --data-dir
      - /etcd-data
      - --listen-client-urls
      - http://0.0.0.0:2379
      - --advertise-client-urls
      - http://0.0.0.0:2379
      - --listen-peer-urls
      - http://0.0.0.0:2380
    restart: always
    networks:
      - leader-election-network

networks:
  leader-election-network:
